### ISSUE TITLE
AdAccount.get_ad_creatives fails on auto-load_next_page

### ISSUE THREAD

**Issue by rorynelsonscott** [facebook/facebook-python-business-sdk#375] opened 2017-07-26 12:46 UTC
We've been making the same API call for months, and today, it has started failing on all of our clients. The request is after an instantiated AdAccount calls get_ad_creatives with the following fields:

`{'fields': 'account_id,body,call_to_action_type,image_url,name,object_story_spec,thumbnail_url,title', 'summary': 'true'}`

The response is as follows:
`
File "/usr/local/lib/python3.4/site-packages/facebookads/api.py", line 759, in __next__
if not self._queue and not self.load_next_page():
 File "/usr/local/lib/python3.4/site-packages/facebookads/api.py", line 793, in load_next_page
params=self.params,
File "/usr/local/lib/python3.4/site-packages/facebookads/api.py", line 326, in call
  raise fb_response.error()
 facebookads.exceptions.FacebookRequestError: 
 Message: Call was not successful
 Method:  GET
 Path:    
https://graph.facebook.com/v2.9/act_10152458720492944/adcreatives?access_token={valid_access_token}&fields=account_id%2Cbody%2Ccall_to_action_type%2Cimage_url%2Cname%2Cobject_story_spec%2Cthumbnail_url%2Ctitle&summary=true&limit=25&after=NjA1NDQ0MTQ4OTU2NgZDZD
Params:  {'fields': 'account_id,body,call_to_action_type,image_url,name,object_story_spec,thumbnail_url,title', 'summary': 'true'}
  Status:  500
  Response:
  { "error": {"type": "OAuthException", "code": 1, "message": "An unknown error has occurred.", "fbtrace_id": "AIjyaPZJwSq" }}
`

When I exclude object_story_spec it finishes. I am simply iterating over the get_ad_creatives with a for loop, constructing a report, and returning the results. As I said, we've been hitting this endpoint for months with no issues until today.

**Comment by rorynelsonscott** [comment] 2017-07-26 20:05
I tried it again this afternoon and had no issues. I would like to understand what was actually going on before closing this out. We received the same error for all of our clients on this same endpoint, which makes me think it was a system issue, though the API status page showed no signs of issues.

**Comment by codytwinton** [comment] 2018-08-27 20:00
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by codytwinton** 2018-08-27 20:00 UTC
