### ISSUE TITLE
Broken import in specs.py

### ISSUE THREAD

**Issue by hdelva** [facebook/facebook-python-business-sdk#476] opened 2018-05-17 14:36 UTC
It seems like the changes in commit 68c08803aec25a089b9346bf2d33ba5c34fb3df7 didn't make it to the PyPI package. Trying to import anything from `spec.py` results in the following import error:

```
  File ".../python2.7/site-packages/facebook_business/specs.py", line 35, in <module>
    from facebook_business.adobjects import adcreativeofferdata
ImportError: cannot import name adcreativeofferdata
```

There is a simple workaround though, `specs.py` just defines aliases so it's possible to just import the original classes directly. Still, might want to update the PyPI package in case there's anyone else who likes using pretty aliases.

**Comment by brandonkane** [comment] 2018-06-05 21:19
The commits were after the 3.0.0 tag.  Would be great if FB could cut a 3.0.1 release with the commits that have been added since the 3.0.0 tag was created and pushed to pypi.  

https://github.com/facebook/facebook-python-business-sdk/compare/3.0.0...master

**Comment by jingping2015** [comment] 2018-08-31 00:02
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-08-31 00:02 UTC
