### ISSUE TITLE
facebookads.adobjects __init__ file is empty

### ISSUE THREAD

**Issue by ghost** [facebook/facebook-python-business-sdk#334] opened 2017-05-09 12:05 UTC
When I want to use a class from the adobjects module I need to do somethings like:
*
`from facebooksads import adobjects

ad_account = adobjects.adaccount.AdAccount(...)`

Reading the docs it looks like this was not intended. When I was reviewing the code, I saw an empty __init__ file in the adobjects module. Could it be that this is the error?

**Comment by avislavkin** [comment] 2017-05-09 12:48
Docs aren't updated for v2.9 .I am also waiting for some updates.
adobjects is folder.
import the class like this 
from facebookads.adobjects.adaccount import AdAccount
and use it
account = AdAccount("act_"+ad_account_id)

**Comment by maritimeMartin** [comment] 2017-05-09 12:53
Thanks for your reply.
Sure I could do it this way, but i am pretty sure, this is not the intended way of usage. 
Imho it would be nice, if somtehing like
`from facebookads.adobjects.adaccount import AdAccount
from facebookads.adobjects.ad import Ad
[...]`
would be present in the __init__ file, so one does not need to use the complete path to the class.

**Comment by daphyFB** [comment] 2017-05-11 17:50
Thanks for reporting Ads API SDK issues.
the __init__ file was intended to be empty, and importing package with the full paths was also intended. However, we do agree that it might be more efficient to list the importing in the __init__ file.
I'll add this as a feature request. Thanks!

**Comment by codytwinton** [comment] 2018-08-27 19:37
This feature request doesn't appear to be actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Closed by codytwinton** 2018-08-27 19:37 UTC
Labels: enhancement
