### ISSUE TITLE
Error from Facebook API Call

### ISSUE THREAD

**Issue by STANAPI** [facebook/facebook-python-business-sdk#505] opened 2018-08-06 08:52 UTC
Hi, I have encountered the below error for the past few days. Could anyone advise on this? Thank you very much.

The Facebook API Call encountered the following exception:

Traceback (most recent call last):

  File "C:\STB\STAN_MG_API\Facebook\fb_page_daily_2nd_degree_impression.py", line 100, in extract

    column_6: str(i['value']['user post']),

KeyError: 'user post'

**Comment by jingping2015** [comment] 2018-08-20 18:40
Can you provide more context ? Like how you call business-sdk ?

**Comment by jingping2015** [comment] 2018-08-31 00:42
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-08-31 00:42 UTC
