### ISSUE TITLE
export report is not working

### ISSUE THREAD

**Issue by chaitu1124** [facebook/facebook-python-business-sdk#507] opened 2018-08-06 15:30 UTC
Hi, 

I used to pull the report based on the report_run_id by using the following URL. Recently I upgraded to facebook_business API version 3.0. It was working till two days back after upgrade aslo but suddenly it starting giving error. 

This URL is not workign any more. Please look into this ASAP. 

https://www.facebook.com/ads/ads_insights/export_report?report_run_id=666555767035076&format=xls&access_token=<token>

Thanks,

**Comment by jingping2015** [comment] 2018-08-17 23:47
How you use our business SDK ? can you provide more source code for testing  ?

**Comment by jingping2015** [comment] 2018-08-31 00:42
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-08-31 00:42 UTC
