### ISSUE TITLE
Api call cannot be made if api is not set

### ISSUE THREAD

**Issue by gianmarco-longhi** [facebook/facebook-python-business-sdk#509] opened 2018-08-15 16:01 UTC
Hi guys, 
I just updated the facebookads library (which was working perfectly until today) but somehow I cannot connect the API anymore.
I'm currently working on a tool which tests ads and I have many API calls to make inside my tool. But whenever it tries to make one, it returns this error:

`facebookads.exceptions.FacebookBadObjectError: Api call cannot be made if api is not set`

I guessed I had to init the service first and therefore I added this outside of my Main:

`FacebookAdsApi.init(app_id, app_secret, access_token)`

But it still returns the same error. Does anybody have a clue?

**Comment by jingping2015** [comment] 2018-08-16 20:04
Can you provide the sample code which havs this issue ？

**Comment by jingping2015** [comment] 2018-08-31 00:43
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-08-31 00:43 UTC
