### ISSUE TITLE
Batch does not return any errors if invalid parameters are sent to the API

### ISSUE THREAD

**Issue by mikeengland** [facebook/facebook-python-business-sdk#372] opened 2017-07-20 11:54 UTC
If I run the following code to create 50 AdSets in a campaign, they are create successfully:

```python
batch = api.new_batch()

for i in range(1, 51):
    params = {
        AdSet.Field.name: 'adset{}'.format(i),
        AdSet.Field.optimization_goal: AdSet.OptimizationGoal.reach,
        AdSet.Field.billing_event: AdSet.BillingEvent.impressions,
        AdSet.Field.bid_amount: 10,
        AdSet.Field.daily_budget: 100,
        AdSet.Field.campaign_id: campaign['id'],
        AdSet.Field.targeting: {
            'geo_locations': {
                'countries': ['US'],
            },
        },
        AdSet.Field.status: AdSet.Status.paused,
    }

    adset = account.create_ad_set(params=params, batch=batch)

batch.execute()
```

If I remove the `AdSet.Field.daily_budget` field, the command completes and does not raise an exception but does not create any AdSets. Is this the expected behaviour? 

I have noticed that the remote_update and remote_create shows failures if you pass in a callback function as per your batch_pause examples, which works fine. I am not sure how you can do this using the create_ad_set function. Also, wouldn't it be better behaviour to at least show some sort of failure to the user when a batch operation fails when a callback isn't passed into the remote_update/create? Otherwise they fail silently.

**Comment by guxufb** [comment] 2017-07-25 07:04
duplicate with #267

**Comment by codytwinton** [comment] 2018-08-27 19:55
This appears to be a duplicate of #267. Closing.

**Closed by codytwinton** 2018-08-27 19:55 UTC
