### ISSUE TITLE
not able to retrieve creative image

### ISSUE THREAD

**Issue by flyfj** [facebook/facebook-python-business-sdk#488] opened 2018-07-08 16:32 UTC
i'm trying to get image url of an ad creative, used the code below:

```
fields = [
        AdCreative.Field.title, AdCreative.Field.name,
        AdCreative.Field.image_url, AdCreative.Field.image_hash,
        AdCreative.Field.link_url
    ]
ad_obj = Ad(ad_id)
data = ad_obj.get_ad_creatives(fields=fields)
```
the data object only contains id, name and creative_id, not even title. 
what did i do wrong to achieve this?

**Comment by FrancYescO** [comment] 2018-07-13 15:05
having similar issue with PHP api... lot of fields are not populated also if i'm requesting it... actually falled on the the thumbnail url that is correctly readed but the image is really small

**Comment by flyfj** [comment] 2018-07-13 20:02
@FrancYescO could you describe how you are able to get the thumbnail image?

**Comment by FrancYescO** [comment] 2018-07-14 09:56
In the php api  Simply i have the THUMBNAIL_URL field

**Comment by jingping2015** [comment] 2018-08-31 00:37
We've been unable to reproduce this bug since it is totally work fine for my test ad, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open or go https://developers.facebook.com/support/bugs/ to report it.

**Closed by jingping2015** 2018-08-31 00:37 UTC
