### ISSUE TITLE
empty report for "fb_page_daily_2nd_degree_impression.py"

### ISSUE THREAD

**Issue by STANAPI** [facebook/facebook-python-business-sdk#522] opened 2018-09-04 04:16 UTC
When running **fb_page_daily_2nd_degree_impression.py**, we are always getting empty reports.

_The Facebook API Call encountered the following exception: 
Traceback (most recent call last):
  File "C:\STB\STAN_MG_API\Facebook\fb_page_daily_2nd_degree_impression.py", line 100, in extract
    column_6: str(i['value']['user post']),
KeyError: 'user post'_

It seems the API could not handle the response. My guess is the response for 'user post' is empty or NULL. Could anyone suggest how to debug it?

**Comment by jingping2015** [comment] 2018-09-04 16:57
Did you try to use our latest package `pip install facebook_business` ? what's the content of `fb_page_daily_2nd_degree_impression.py` ?

**Comment by jingping2015** [comment] 2018-09-10 22:02
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-09-10 22:02 UTC
